# Spring Boot Properties
spring.application.name=healthrx-java-assignment

# Logging
logging.level.com.healthrx.assignment=DEBUG

# Since there are no controllers, we can disable the web server to save resources
spring.main.web-application-type=none
